# Simple workflow for deploying static content to GitHub Pages
name: Build and Deploy

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Main Repository
        uses: actions/checkout@v4
        with:
          repository: SwapMarket/swapmarket.github.io
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      # Add base to vite.config.js
      - name: Update vite.config.mjs
        run: |
          sed -i "s|base: '/',*$|base: '/testnet/',|g" vite.config.mjs
      # Add base to index.mts
      - name: Update index.tsx
        run: |
          sed -i 's|base = "/";|base = "/testnet/";|g' src/index.tsx
      # specify testnet 
      - name: Copy config
        run: npm run testnet
      - name: Build
        run: npm run build
      - name: Setup Pages
        uses: actions/configure-pages@v4
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload dist folder
          path: './dist'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
